### PR TITLE
Remove TONE_EXTRA from chirp_common.py - fixes #10795

### PR DESCRIPTION
**Pull request by KC9HI**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).
* All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by KC9HI** [comment]
@kk7ds This is what I have so far. The tones show up in the list but generates and error when the tone is selected ('xx.x' is not in valid list:). As expected, this then fails the driver tests.

I cannot find a single driver that is supposed to have added tones that works. Only the driver where tones are removed seem to be correct. I suspect that when I asked to add 'rf.valid_tones', something got overlooked in the implementation. Adding DTCS codes works fine.

Is this something that you need to look at, or is that still something that is left out of all drivers attempting to add additional CTCSS tones?

**Comment by kk7ds** [comment]
Yep, a little more work required to make the chirp_common stuff agree to let you set custom lists. I'll push up a change in a sec, can you give it a once-over for me?

**Comment by KC9HI** [comment]
I did a quick test. The radios in the drivers that I am working on, RB15/RB615, AT-5888UV and VV898 all display the added tones and the tones can be selected without causing any errors. Yay!

There are about a half dozen drivers with added tones that do not show up. This is because they do not have an rf.valid_tones entry. As a quick test I added this to one of the drivers and it works as expected.

Once these are merged and the dust settles, I will make a point to get the other drivers with extra tones updated so that they will be available for use.

So it is two thumbs up from me.

**Comment by kk7ds** [comment]
Cool, thanks!

**Pull request merged**
