### PR TITLE
Update ga-510

### PR DESCRIPTION
**Pull request by lunapiercook**
Remove Language from SHX8800 family (also unavailable from radio menu)

# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by lunapiercook** [comment]
I believe this is ready to go. I did remove the Signus ==> Cignus name change from this version, so this only removes the Language option from the SHX8800 family.

**Comment by kk7ds** [comment]
Please squash these into a single commit with a reasonable commit message and reference a bug (all items in the checklist above) and I'll merge.

**Comment by lunapiercook** [comment]
Ok, might be a stupid question: So, I need to create that bug, i.e. "Language feature unavailable in the SHX8800 family.", Yes? (Believe me when I say I'm taking a LOT of notes...)
-------- Original message --------From: Dan Smith ***@***.***> Date: 3/16/23  7:10 PM  (GMT-05:00) To: kk7ds/chirp ***@***.***> Cc: lunapiercook ***@***.***>, Author ***@***.***> Subject: Re: [kk7ds/chirp] Update ga-510 (PR #553) 
Please squash these into a single commit with a reasonable commit message and reference a bug (all items in the checklist above) and I'll merge.

**Comment by kk7ds** [comment]
Yes (which I see you've done now).

**Pull request closed without merging**
