### PR TITLE
K5 Plus: Register new model -> child of 5RM driver

### PR DESCRIPTION
**Pull request by hgrasman**
Fixes: #11119

# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues). Do this with the pattern `Fixes #1234` or `Related to #1234` so that the ticket system links the commit to the issue.
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).
* All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* The first line of every commit is emailed to the users' list after each build. It should be short, but meaningful for regular users (examples: "thd74: Fixed tone decoding" or "uv5r: Added settings support").
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by hgrasman** [comment]
Radio Baofeng_K5_Plus should ~~not~~ override check_set_memory_immutable_policy

Just like the 17 pro and 5RM

**Comment by hgrasman** [comment]
@kk7ds 

Hey Dan. Now sure how to decypher what's going on here. The offending code seems to be something you added to the other models after some of my changes. I'm about to add another model inheriting from this driver, so I'd like to understand.

**Comment by kk7ds** [comment]
Which are you talking about... the unit failure? If so, you need to add this radio to the immutable whitelist in the test file (`test_chirp_common`) **if** the airband override in the 5RM applies to the 5RH as well. If it doesn't, then it shouldn't be a subclass of it and instead should subclass the 17Pro itself.

**Comment by hgrasman** [comment]
> Which are you talking about... the unit failure? If so, you need to add this radio to the immutable whitelist in the test file (`test_chirp_common`) **if** the airband override in the 5RM applies to the 5RH as well. If it doesn't, then it shouldn't be a subclass of it and instead should subclass the 17Pro itself.

I suppose I don't know the answer to that, other than that the new radio in question is "identical" with a different form factor. So I would assume that's correct. Unless you oppose, I'll add it. 

I assume the test matrix is mad because I added a model without updating unit tests? Do you have a one-pager tutorial for how to do that properly?

**Comment by kk7ds** [comment]
If you don't know for sure I I think you should not subclass the special one. We can always fix it later if people complain. Perhaps you can tell from the public specs whether it supports airband?

For the matrix just rebase on master, delete the file and re-run the `makesupported` to regenerate the file, commit/resolve/whatever and you should be good. If you cant figure it out I can do it for you.

**Comment by hgrasman** [comment]
> If you don't know for sure I I think you should not subclass the special one. We can always fix it later if people complain. Perhaps you can tell from the public specs whether it supports airband?
> 
> For the matrix just rebase on master, delete the file and re-run the `makesupported` to regenerate the file, commit/resolve/whatever and you should be good. If you cant figure it out I can do it for you.

I see now that this is just enforcing the AM mode. Yes it is appropriate for this radio, so I'll add the whitelist. This radio is a 5RM in hardware and firmware (just a cheap attempt to steal quansheng k5 customers).

I'll see if I can figure out the test matrix. I'm just ignorant about how that works at the moment.

**Comment by hgrasman** [comment]
@kk7ds 

Update I don't think I'm figuring this out. I think I've got a 40% correct guess on what's going on. If you're up for it, please explain what to do, and do it for me this time.

**Pull request merged**
