### PR TITLE
Update h777.py

### PR DESCRIPTION
**Pull request by Richisfree**
Frequency range modification for BF-888S radios from https://www.stix.id.au/wiki/Baofeng_BF-888S_and_Aussie_UHF_CB

### CODE REVIEW

**Comment by Richisfree** [comment]
Hi Dan,

My apologies for creating this pull request back to your repo.  I thought I was pulling to my own fork.  Nevertheless, the motivation for this change was to allow programming the BaoFeng BF-888S to be legally used without an ACMA license in Australia.  The link in the original pull request comment has the background.  It's a very simple change to the repository and the author of linked post professes that it works (despite the manufacturer's reported frequency range being limited to a narrower band).  I'm about to run this locally and confirm that, if it doesn't work I'll delete this pull request.  Also, feel free to delete it if you see fit, no offence taken.  

Rich

**Comment by kk7ds** [comment]
Okay, maybe @KC9HI can opine here. I imagine it's a fine change to make for everyone. However, the (first line of the) commit message needs to be something meaningful to the users, as it gets sent to the mailing list for the build it is included in. Just "update this file" doesn't tell people what the change is :)

**Comment by KC9HI** [comment]
This is probably fine. Even 520000000 might be as well. I just don't have any way here to test so I generally set the band limits to values that I can see in the image or the manufacturer specifies in the user manual or CPS.

**Comment by kk7ds** [comment]
Okay, I'll leave it as-is but fix the commit message so we can get it merged for tomorrow.

**Comment by Richisfree** [comment]
Hi Dan and @KC9HI I tested this today on the radios, took me a while (was unable to build it on my mac, python apps are foreign to me) but was able to test the driver file by uploading as a module to chirp in developer mode.  The radios certainly worked on the frequencies I tested.  I was only testing on Australian amateur CB bands though (as high as 477MHz) but everything worked perfectly.  Rich

**Pull request merged**
