### PR TITLE
5RM: updated class to properly represent medium tx power

### PR DESCRIPTION
**Pull request by hgrasman**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).
* All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* The first line of every commit is emailed to the users' list after each build. It should be short, but meaningful for regular users (examples: "thd74: Fixed tone decoding" or "uv5r: Added settings support").
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by hgrasman** [comment]
Quick fix for myself. I figure I'll continue updating the 5RM driver for myself, so time to learn how to contribute.

I'm new to git so please be helpful if I'm not understanding the process. My next pull request will not be this small. (unless it's okay to make incremental progress like this)

**Comment by kk7ds** [comment]
Per the guidelines, please file a bug on the chirp page explaining the problem and reference it from your commit message like "Fixes #xxx" to properly link them. Also please squash these three commits into just one because they're just one logical change (we don't need to add three things to the forever history because you didn't have the proper style initially). Just force push to this, please don't open another PR.

Incremental changes are definitely appreciated over large monolithic ones. Please arrange commits into logical changes, but it's great if you can group several small logical changes in a single PR. Bugs on the chirp site for your plans will help people know what you're planning to avoid duplication.

Thanks!

**Comment by kk7ds** [comment]
Oh sorry, I see you've got a bug in the topic, please just put that in your squashed commit message so it links properly :)

**Comment by hgrasman** [comment]
Squashed successfully? 

Fixes bug #11102

**Comment by kk7ds** [comment]
Yep squash looks good, but you need the fixes tag in the commit message, not just in a github comment (the bug tracker can't see the latter). If you're doing git at the command line something like:
```
$ git commit --amend
< add fixes tag to the commit message after the first line >
$ git push --force
```

If you run into trouble, I'll do it for you. I'll plan to merge this with a few other things early next week for a build. Thanks!

**Comment by kk7ds** [comment]
Perfect thanks :)

**Comment by kk7ds** [comment]
Since the other set contained this, this no longer has anything to change so I'll close.

In the future, a single PR for work on a single driver is totally cool, you could have just stacked those commits on here to build on it. I'd just like to avoid PRs that make lots of unrelated changes as they become hard to review and merge one part without the other.

Thanks!

**Pull request closed without merging**
