### PR TITLE
Update turkish language

### PR DESCRIPTION
**Pull request by TA1AUB**

### CODE REVIEW

**Comment by TA1AUB** [comment]
Can you please edit the file like this?

**Comment by kk7ds** [comment]
Yeah I think it's okay now, I should make the check not so concerned about the file location lines. I'll pull this down and rebuild to check. Thanks for your work on this :)

**Comment by kk7ds** [comment]
Can you confirm this looks okay? The build will create multiple strings to break at 80 columns which is another reason the check complains. I'm guessing the editor you are using rewraps them or something. Not a problem, it's easy to fix.

**Comment by TA1AUB** [comment]
Everything looks okay.

**Pull request merged**
