### PR TITLE
ft8100: Changed upload and downlod prompt

### PR DESCRIPTION
**Pull request by N7XSD**
Added classmethod get_prompts to give upload and download instructions specific to the FT-8100.

### CODE REVIEW

**Comment by kk7ds** [comment]
You marked the strings for translation, which means the catalog needs to be regenerated. I can just do this for you if you're not able, but:
```
$ make -C chirp/locale clean all
```
will do it.

Also, next time `git push -f` will re-use the same PR, which is preferable :)

Thanks!

**Comment by N7XSD** [comment]
Thanks.

Followed both of your suggestions. I'm still learning git.

**Comment by kk7ds** [comment]
Aren't we all :)

Thanks!

**Comment by kk7ds** [comment]
I just rebased and fixed a typo in the first commit subject (since that gets emailed to about 2000 people when the next build happens).

**Pull request merged**
