### PR TITLE
Some more wxUI tweaks

### PR DESCRIPTION
**Pull request by kk7ds**
- Make the minimum column width wider on Linux
- Allow selecting page at startup from CLI
- Allow starting some actions from the CLI

### CODE REVIEW

**Comment by kk7ds** [comment]
@jebbgrenham Interested in your thoughts on two things here. First, I think you're running linux. On all the (two) linux flavors I've tried, the GTK widgets are huge and barely fix in the cell while editing things like tone/mode on memories. This makes them a little wider by default so that it fits better. Curious what you're seeing and if this looks better.

Second, this allows you to jump straight to query_rrus (for example) from the command-line, which I assume will make it easier to test the RR stuff without so much mouse action. I know it sure would have for the RB stuff.

**Comment by jebbgrenham** [comment]
Screenshot from 2022-12-14 12-36-42

**Comment by kk7ds** [comment]
Actually, that's a different problem. I'm talking about editing fields directly in the spreadsheet.

This is before the change:

image


image

and this is after:

image

image

**Comment by jebbgrenham** [comment]
Screenshot from 2022-12-15 11-51-50

**Comment by kk7ds** [comment]
Cool, looks decent.

**Comment by jebbgrenham** [comment]
Yup!

**Pull request merged**
