### PR TITLE
Update gmrsv2.py driver to use mem.immutable - #10288

### PR DESCRIPTION
**Pull request by KC9HI**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by kk7ds** [comment]
Do you have all the ones done in your bug, or are you just doing these one at a time? It's fine to put them all into one PR if you want, don't step through them one at a time on my account. Might be nice for them to be one commit per driver, but all those can be in the same PR. Or one commit if it's easier.

**Comment by kk7ds** [comment]
I'll go ahead an merge this one regardless.

**Comment by KC9HI** [comment]
I am doing them one at a time but I have 2 more that I will be submitting in a few minutes. I can create separate issues if doing it this way is a problem.

**Comment by kk7ds** [comment]
Nope, totally cool, just didn't want you to have to submit them one at a time if they're all done. But all good. We're going to run out of stuff at some point to keep up the pace, so all good if you've got a few days of these on the horizon :P

**Pull request merged**
