### PR TITLE
Allow KG-UV9D Plus driver to open more radio revision numbers using 9D Plus memory map

### PR DESCRIPTION
**Pull request by mrtjr1**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by kk7ds** [comment]
I think you based this on an old commit and so it's now stuck with conflicts. I'll try to pull it down and get it straightened out for you in a sec.

**Comment by mrtjr1** [comment]
I based it off of my branch and commit that added the 9PX.   I probably
missed a step before making this commit.

**Comment by kk7ds** [comment]
Yeah, I think the reason is because I rebased your original commit for you, but if you based your fix on top of your un-rebased local commit, it tried to submit that whole stack as new, with a merge commit and then thought your copy of the original conflicted with the one I rebased for you. If you see merge commits in your PR, that generally means something isn't right unless you're specifically trying to do something funky.

Anyway, no worries, it was easy to fix.

**Comment by mrtjr1** [comment]
Does putting multiple instances of 
Fixes: XXXX
close all the issues listed or just the first, or none at all.
Is there a preferred method to close multiple issues with the same PR?

**Comment by kk7ds** [comment]
Yep, you can do multiple Fixes bugs, just make sure it's in one of the commit messages, not the PR description or title, because redmine won't see the latter.

But yeah, if you're closing more than one bug in a single commit, do multiple fixes statements. If you have a PR with multiple commits, one per bug, then just do the fixes in the appropriate commits within the PR. Redmine doesn't know anything about PRs, just commits.

**Comment by mrtjr1** [comment]
OK I think I put 3 Fixes statements in the latest commit description.
 We'll see if I did it correctly.

**Pull request merged**
