### PR TITLE
FT818: Add PMS as possible scan mode.

### PR DESCRIPTION
**Pull request by wutje**
This fixes a Python error rendering the Settings tab unavailable. Note: tested this on a FT818. I cannot verify this for a FT817.

# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).
* All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by wutje** [comment]
Some CI check fails, but I do not see how my change triggers this failure.
Is there something I can do or missed?

**Comment by kk7ds** [comment]
It's not your fault and not a required check, so you can ignore. Can you please file a bug on the chirp site with this and add a `Fixes: #1234` tag in the commit message per the PR Guidelines above? Thanks!

**Comment by kk7ds** [comment]
I just rebased this for you and filed a bug to tag in the commit message:

https://chirp.danplanet.com/issues/10770

If you could attach a debug log showing the failure to that for posterity, I'd appreciate it.

**Comment by wutje** [comment]
The error was:

```
ERROR: Failed to run get_settings(, )
Traceback (most recent call last):
  File "/home/wouter/devel/chirp/chirp/wxui/common.py", line 276, in do_radio
    job.result = getattr(self._radio, fn)(*a, **k)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wouter/devel/chirp/chirp/drivers/ft817.py", line 1033, in get_settings
    options[_settings.scn_mode]))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
ERROR: Context raised unexpected_exception
Traceback (most recent call last):
  File "/home/wouter/devel/chirp/chirp/wxui/settingsedit.py", line 49, in _initialize
    raise job.result
  File "/home/wouter/devel/chirp/chirp/wxui/common.py", line 276, in do_radio
    job.result = getattr(self._radio, fn)(*a, **k)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wouter/devel/chirp/chirp/drivers/ft817.py", line 1033, in get_settings
    options[_settings.scn_mode]))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by wutje** [comment]
Thank you for the quick fix turn around. I traveling so I cannot be this fast :)

**Pull request merged**
