### PR TITLE
Upgrade gmrsv2.py to use mem.immutable (revisited) - #10288

### PR DESCRIPTION
**Pull request by KC9HI**
This model supports "fully customizable channels" which created some additional challenges.

# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by KC9HI** [comment]
I really like how this works not. It almost passed with flying colors and I was about to tell you to go ahead and merge this. Unfortunately while copying channels from my radio into a GMRS-V2 image, 3 channels encountered errors. The errors for all 3 were the same so I just copied one of them. But I will attach my image file so you can test. The problem channels are 10, 11 and 12. One uses "split" and the other 2 use "-" for the duplex.
[GMRS-V2_errors.zip](https://github.com/kk7ds/chirp/files/10530538/GMRS-V2_errors.zip)

**Comment by KC9HI** [comment]
Oops. I like how it works 'now'.

**Comment by kk7ds** [comment]
Ah yep, just a typo basically. Fixed now, I think, thanks!

**Comment by KC9HI** [comment]
OK. Great. I am in the process of adding RB17P to this. Will push it to you soon.

**Comment by kk7ds** [comment]
Roger, I'll wait for that before merge, thanks!

**Comment by KC9HI** [comment]
With what you have done, there shouldn't be a need for validate_memory() like being added to GMRS-V2, right?

**Comment by kk7ds** [comment]
No, `validate_memory()` *is* required. That's how we get the warning that "you pasted duplex + but I'm going to change it to off because I have to". Without that, the user gets no indication why duplex was changed to off, and I definitely prefer that we explain to them so they're not thinking it's a bug.

**Comment by KC9HI** [comment]
OK. Once I add validate_memory(), it should be ready. I need to a a "-f" to force it, right?

**Comment by kk7ds** [comment]
If you're up-to-date and just adding another commit on top, then you don't. However, if you checked out the branch before I made the typo fix then yeah, just push -f and I'll re-fix it after you do.

**Comment by kk7ds** [comment]
Ah, looks like you did commit `--amend` so the RB17 is in the same commit as the GMRSv2. That's okay I'll just update the commit message when I re-fix the typo.

**Comment by KC9HI** [comment]
Yeah. I didn't realize could leave the --amend of and start another commit on the same branch. I'll have to remember that for the future.

**Comment by kk7ds** [comment]
Yep, I regularly put several related commits in one PR. Anyway, no big deal, should be good now. Thanks!

**Comment by KC9HI** [comment]
This is great! I can now go back to working on my list. Thank you.

**Pull request merged**
