### PR TITLE
SP calling frequencies stock config

### PR DESCRIPTION
**Pull request by szporwolik**
Created stock config with calling frequencies and frequently used frequencies for Poland (SP).

### CODE REVIEW

**Comment by kk7ds** [comment]
Thanks. Are you able to run chirp direct from git? If so, I can get you to test the przemienniki code before I merge.

**Comment by szporwolik** [comment]
Yes, with no problem - I've actually set up a full environment.

**Comment by kk7ds** [comment]
Great thanks, I'll mention you on the PR so you can look.

In the meantime, can you squash these two commits into one so we don't have the rename in the history? I can do it for you if not.

**Comment by szporwolik** [comment]
Closing, will open new one with squashed commits.

**Pull request closed without merging**
