### PR TITLE
H3 models need to be optimized

### PR DESCRIPTION
**Pull request by songjunbiao**
New features and bugs to be fixed.

### CODE REVIEW

**Comment by kk7ds** [comment]
This is a commit from November, which has already been applied and thus can't be merged. What are you trying to change? You need to rebase your change on top of master, which has moved since your commit.

**Comment by songjunbiao** [comment]
> 这是 11 月份的提交，已经应用，因此无法合并。你想改变什么？您需要在 master 之上重新调整您的更改，该更改自您提交以来已发生变化。

H3, we've done a frequency range expansion on this model, and I need to modify it. How do I do that? Do I need to recreate the branch?

**Comment by songjunbiao** [comment]
> This is a commit from November, which has already been applied and thus can't be merged. What are you trying to change? You need to rebase your change on top of master, which has moved since your commit.

H3, we've done a frequency range expansion on this model, and I need to modify it. How do I do that? Do I need to recreate the branch?

**Comment by kk7ds** [comment]
You can rebase your branch, but typically you want to fetch origin (i.e. update from my tree) then checkout a new branch for new work.

**Comment by kk7ds** [comment]
You're using the master branch in your tree, which you should not be doing.

Fetch my remote, then checkout a topic branch from mine, something like this:

```
$ git checkout origin/master -b update-h3-range
( make your changes )
$ git commit -a
```

Then push the update-h3-range branch to github

**Comment by kk7ds** [comment]
Are you going to update this? A number of people have reported issues with this driver and I'm unable to help them. I'm curious if your changes will address these bugs, and if not, can I point you to them so you can look?

**Pull request closed without merging**
