### PR TITLE
[UV-50X2_G2] Add Baofeng Tech UV-50X2_G2

### PR DESCRIPTION
**Pull request by kk7ds**
Baofeng Tech is releasing a second generation version of the BTech UV-50X2. This patch adds support for the BTech UV-50X2_G2.

fixes #10126

### CODE REVIEW

**Comment by kk7ds** [comment]
@KC9HI Looks like this is failing the detect test because the original image triggers both drivers. Are you not seeing that locally?

**Comment by KC9HI** [comment]
On Thu, Nov 17, 2022 at 8:41 PM Dan Smith ***@***.***> wrote:
>
> @KC9HI Looks like this is failing the detect test because the original image triggers both drivers. Are you not seeing that locally?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

I didn't see it. Probably because I added it as an afterthought. I
performed a run_all_tests without the added image, decided to add the
image and then just performed the individual test for the added image.

Jim

**Comment by kk7ds** [comment]
Okay, I wonder why the metadata isn't distinguishing them for us, since they have different MODEL values, and we don't seem to be tripping up on the other subclasses...

**Comment by KC9HI** [comment]
On Thu, Nov 17, 2022 at 8:52 PM Dan Smith ***@***.***> wrote:
>
> Okay, I wonder why the metadata isn't distinguishing them for us, since they have different MODEL values, and we don't seem to be tripping up on the other subclasses...

Would it be because I should have told CHIRP to only use metadata for
the new model?

**Comment by kk7ds** [comment]
Ah, I see, the old one is pre-metadata. So yeah, probably need the new one to only work with metadata like some of the others in that file.

Lemme try to do that real quick to save a round trip.

**Comment by KC9HI** [comment]
I just switched back to Windows and performed a run_all_tests. There
were no errors reported. I also loaded the original and new images
without any errors.

Jim

**Comment by kk7ds** [comment]
Yeah, `run_all_tests.bat` doesn't run the unit tests. There is a detect test in the driver set, but it's non-deterministic and doesn't always catch these, so I wrote a unit test (years ago) that brute-forces every model and every image to make sure there are no leaks.

**Comment by kk7ds** [comment]
I think this should work on Windows:

`python -m unittest discover -s ./tests/unit -v`

If so, we can add that to `run_all_tests.bat` if you want...

**Comment by KC9HI** [comment]
This was the output...

D:\chirp.hg>python -m unittest discover -s ./tests/unit -v
test_bit_array (test_bitwise.TestBitType) ... ok
test_bit_array_fail (test_bitwise.TestBitType) ... ok
test_bitfield_u16 (test_bitwise.TestBitfieldTypes) ... ok
test_bitfield_u24 (test_bitwise.TestBitfieldTypes) ... ok
test_bitfield_u8 (test_bitwise.TestBitfieldTypes) ... ok
test_bitfield_ul16 (test_bitwise.TestBitfieldTypes) ... ok
test_bitfield_ul24 (test_bitwise.TestBitfieldTypes) ... ok
test_bbcd (test_bitwise.TestBitwiseBCDTypes) ... ok
test_bbcd_array (test_bitwise.TestBitwiseBCDTypes) ... ok
test_lbcd (test_bitwise.TestBitwiseBCDTypes) ... ok
test_lbcd_array (test_bitwise.TestBitwiseBCDTypes) ... ok
test_int_array (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_u16 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_u24 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_u32 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_u8 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_ul16 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_ul24 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_type_ul32 (test_bitwise.TestBitwiseBaseIntTypes) ... ok
test_char (test_bitwise.TestBitwiseCharTypes) ... ok
test_string (test_bitwise.TestBitwiseCharTypes) ... ok
test_string_invalid_chars (test_bitwise.TestBitwiseCharTypes) ... ok
test_string_wrong_length (test_bitwise.TestBitwiseCharTypes) ... ok
test_comment_cppstyle (test_bitwise.TestBitwiseComments) ... ok
test_comment_inline_cppstyle (test_bitwise.TestBitwiseComments) ... ok
test_missing_semicolon (test_bitwise.TestBitwiseErrors) ... ok
test_seek (test_bitwise.TestBitwiseSeek) ... ok
test_seekto (test_bitwise.TestBitwiseSeek) ... ok
test_struct_one_element (test_bitwise.TestBitwiseStructTypes) ... ok
test_struct_two_elements (test_bitwise.TestBitwiseStructTypes) ... ok
test_struct_writes (test_bitwise.TestBitwiseStructTypes) ... ok
test_chirp_common (unittest.loader.ModuleImportFailure) ... ERROR
test_directory (unittest.loader.ModuleImportFailure) ... ERROR
test_import_logic (unittest.loader.ModuleImportFailure) ... ERROR
test_mappingmodel (unittest.loader.ModuleImportFailure) ... ERROR
test_memedit_edits (unittest.loader.ModuleImportFailure) ... ERROR
test_platform (unittest.loader.ModuleImportFailure) ... ERROR
test_settings (unittest.loader.ModuleImportFailure) ... ERROR
test_shiftdialog (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_chirp_common (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_chirp_common
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_chirp_common.py", line 6, in <module>
    import mock
ImportError: No module named mock


======================================================================
ERROR: test_directory (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_directory
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_directory.py", line 7, in <module>
    from tests.unit import base
  File "tests\unit\base.py", line 2, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: test_import_logic (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_import_logic
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_import_logic.py", line 1, in <module>
    from tests.unit import base
  File "tests\unit\base.py", line 2, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: test_mappingmodel (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_mappingmodel
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_mappingmodel.py", line 16, in <module>
    from tests.unit import base
  File "tests\unit\base.py", line 2, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: test_memedit_edits (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_memedit_edits
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_memedit_edits.py", line 1, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: test_platform (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_platform
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_platform.py", line 17, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: test_settings (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_settings.py", line 16, in <module>
    from tests.unit import base
  File "tests\unit\base.py", line 2, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: test_shiftdialog (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_shiftdialog
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\chirp.hg\tests\unit\test_shiftdialog.py", line 2, in <module>
    import mox
ImportError: No module named mox


----------------------------------------------------------------------
Ran 39 tests in 0.031s

FAILED (errors=8)

D:\chirp.hg>python -m unittest discover -s ./tests/unit -v

**Comment by kk7ds** [comment]
That's because you need mock and mox installed. Tox does this for you, but you can do it manually. Hopefully this works on windows too:

`python -mpip install mock mox`

**Comment by KC9HI** [comment]
On Thu, Nov 17, 2022 at 9:52 PM Dan Smith ***@***.***> wrote:
>
> That's because you need mock and mox installed. Tox does this for you, but you can do it manually. Hopefully this works on windows too:
>
> python -mpip install mock mox

Yes. That worked. The previous command still results in 6 errors. One
is the failure that we were looking for related to detecting both the
UV-50X2.img and UV-50X2_G2.img.

All the rest seem to have something to do with metadata but I am not
sure what. They all have [Errno 13] Permission denied... errors.

Jim

**Pull request merged**
