### PR TITLE
Add TDH8 driver

### PR DESCRIPTION
**Pull request by Sandmann34**
Add tdh8 driver, use the test image, put the new file into the tools run style check

### CODE REVIEW

**Comment by Sandmann34** [comment]
I found a problem "Failed to parse my version '0.3.0dev': invalid literal for int() with base 10: '0dev'" How to solve it to pass Tests / Driver tests

**Comment by kk7ds** [comment]
No, that's not an error, it's just a warning, it's always logged when running development (i.e. not-released) versions because the app version doesn't match the pattern it's looking for.

Have you run the tests locally? Just run:
```
$ tox
```

and you will reproduce the failures locally. The driver tests are failing in your driver, so they are problems you need to fix.

Also, you have merged master and py3 in your commit [17f6bf6](https://github.com/kk7ds/chirp/pull/299/commits/17f6bf6b7b3ab9e9853eef768dde832005217168). That's why you have other people's commits in your PR. You need to submit clean commits on top of py3. You probably did a `$ git merge py3` when you should have done a `git rebase py3`. You need to fix that before it could be merged.

**Comment by kk7ds** [comment]
To be clear, these are the four driver tests you're failing:
```
FAILED tests/test_drivers.py::TestCase_TIDTDH8::test_brute_force - tests.run_...
FAILED tests/test_drivers.py::TestCase_TIDTDH8::test_copy_all - ValueError: `...
FAILED tests/test_drivers.py::TestCase_TIDTDH8::test_edges - chirp.settings.I...
FAILED tests/test_drivers.py::TestCase_TIDTDH8::test_settings - tests.run_tes...
==== 4 failed, 1273 passed, 214 skipped, 296 warnings in 195.74s (0:03:15) =====
```

**Comment by Sandmann34** [comment]
Yes, I didn't run the test tox locally, I will test it locally in the later debugging, but I ran ./test/run_test.py, and after troubleshooting some errors, I found a difficult error:

**TID TD-H8 BruteForce FAILED: Field `tmode' is `', expected `Tone'**

After I set the array：

**rf.valid_tmodes = ["", "Tone", "TSQL", "DTCS", "Cross"]** 

to nothing, it passed the test
Is it an error caused by me doing a self-written method when dealing with "tmode"?
For issues with other people's commits in the PR, I'll fix it after I fix this driver.

thanks.

**Comment by kk7ds** [comment]
> Yes, I didn't run the test tox locally, I will test it locally in the later debugging, but I ran ./test/run_test.py, and after troubleshooting some errors, I found a difficult error:

Running `run_tests.py` manually is not the same as running via `tox` (and thus `pytest`), especially on the py3 branch, FYI.

> **TID TD-H8 BruteForce FAILED: Field `tmode' is `', expected `Tone'**
> 
> After I set the array：
> 
> **rf.valid_tmodes = ["", "Tone", "TSQL", "DTCS", "Cross"]**

This test is checking that if it hands you a memory with `tmode=Tone` that you give it the same memory back when it does a `get_memory()`. The failure is generally a bug in your tone mode calculation logic, where you return a different `tmode` than the test tried to set. The test is trying to ensure that you are consistent with the rest of chirp such that you don't take a `tmode=Tone` memory and return a `tmode=Cross` result, or similar. In this case, it tried to set a memory with `Tone` and then a subsequent `get_memory()` of the same location returned a `tmode` of empty (i.e. no tone).

All drivers have to pass these tests and it's a struggle for some people, but the tests ensure that the drivers behave as the GUI expects them.

> to nothing, it passed the test Is it an error caused by me doing a self-written method when dealing with "tmode"?

No, it's okay (and expected) to write your own method to handle `tmode`, it just means that your method is not quite right. You might look for the `debug.log` or `logs/` directory for more details about what it's trying to set and what it's getting back.

**Pull request closed without merging**
