### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by dforsi**
This PR fixes
- one statement (s/pring/print/ in [chirp/drivers/vx6.py](https://github.com/kk7ds/chirp/compare/master...dforsi:chirp:fix/typos?expand=1#diff-8c21f16e2bf5bd2d2e60541e1485324bf97073be98772e3f5487e2bf8f6ac678))
- some strings that are passed as arguments of ```RadioSetting()``` for which I don't understand if this breaks the code
- other strings that are either docstrings or arguments of ```LOG()```
- some comments.

I'm sorry I couldn't run the tests due to missing dependencies on my local machine. 
Let me know if any changes to this PR are needed.

### CODE REVIEW

**Review by goldstar611 — APPROVED** [review]
All of the changes look sane to me, plus I learned something new (codespell tool).

**Comment by kk7ds** [comment]
I dunno why the github checks didn't run on this, but I pulled it locally and it seems to work...

**Comment by goldstar611** [comment]
GitHub has a security setting (that can be changed) where it doesn't run Actions on pull requests from new contributors by default IIRC

**Comment by kk7ds** [comment]
Yeah, it just asks me to approve each first time new PR. Not in this case, for some reason.

**Pull request merged**
