### PR TITLE
add menu items before enabling/disabling

### PR DESCRIPTION
**Pull request by mabrand**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by mabrand** [comment]
This fixes the failure to display the properties menu when right-clicking on a memory row. Problem observed running under Ubuntu 20.10.

Traceback (most recent call last):
  File "/home/brand/gits/chirp/chirp/wxui/memedit.py", line 1153, in _memory_rclick
    del_block_item.Enable(not self.busy)
wx._core.wxAssertionError: C++ assertion "m_menuItem" failed at ../src/gtk/menu.cpp(756) in Enable(): invalid menu item

**Comment by kk7ds** [comment]
Okay, I don't see that on 20.04 or 22.04. Can you confirm what python and python3-wxgtk you're running? I'll file a bug for you and report and update the commit message so we have the record.

**Comment by kk7ds** [comment]
Ah, you meant 22.10 (kinetic) not 20.10 (groovy) okay.

**Comment by mabrand** [comment]
Oops, sorry about that.

**Pull request merged**
