### PR TITLE
ga510.py: add 'reset' v2

### PR DESCRIPTION
**Pull request by KC9HI**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).
* All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by KC9HI** [comment]
I gave up on 'finally:'. I couldn't get it to pass the 'driver' test.

**Comment by kk7ds** [comment]
I'm guessing one of the clone tests? I imagine you need to swallow any exception you get in the `reset()` function which will re-raise something other than `RadioError` on the error test. If you don't mind, let me take a shot tomorrow and I'll see if I can get it to work.

**Comment by kk7ds** [comment]
This is what I had in mind. Works for me with a ga510 and passes tests. @KC9HI let me know if you're okay with this. Your way definitely works, but it's easier to miss a case (or add a new one that doesn't reset).

**Comment by KC9HI** [comment]
I did look at the tk3140.py driver last night. It looked like it utilized 'finally:' in the manner that I was looking for. I suspected that something might need to be done to reset() but it was too close to midnight, so I gave up and decided to take the 'comfortable' path to a solution for the problem.

I have torture tested with a Retevis RA85 and RA685. It is nice to not have to power cycle the radio after an error encountered or upload completed.

Thanks for helping me get this working, @kk7ds. This will definitely be my preferred method to use whenever a radio has an 'exit' command to end cloning.

**Pull request merged**
