### PR TITLE
Verify VX-2

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Tested read/modify/write/verify for editing: memory frequencies/labels, settings (opening message text).
System: macOS 10.14.6 and SparkFun DEV-14050 (CH340G) breakout

# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Completed improperly, will try again.

**Comment by kk7ds** [comment]
No need to close this, just push up a change with force. But if you need me to I can "do it right" from what you have here, just reopen and let me know and I can push it.

**Comment by thomasrussellmurphy** [comment]
Yeah, it'd probably be easier if you re-do this from the top since I didn't do the full edit process back to the `py3_driver_testers.txt` source and I'm not sure how long it'll take me to get the build environment together to complete the instructions correctly.

**Comment by kk7ds** [comment]
Looks like you deleted the branch already so I can't push to this, so I pushed it to #422 .

**Pull request closed without merging**
