### PR TITLE
Wrong usage of hasattr

### PR DESCRIPTION
**Pull request by creeble**

### CODE REVIEW

**Comment by kk7ds** [comment]
Crap, I even downloaded to test it, but then didn't.

**Comment by creeble** [comment]
My fault, oof.
Seems like I also did the PR wrong?  I thought I had resync'd from your repo first, but it seems to want to add 4 commits?

**Comment by kk7ds** [comment]
I'll fix it up, just give me a bit.

**Comment by kk7ds** [comment]
Looks like you have "allow edits from maintainers" disabled? That prevents me from pushing to this PR. If you prefer I can push to a new PR instead of yours.

**Comment by kk7ds** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by kk7ds** [comment]
Sorry, nevermind, it was because you're doing a PR from your master branch and I had to change it on my end.

And yeah, sorry that the bad hasattr syntax was from me, I was just rushing and not thinking, so my bad.

**Comment by creeble** [comment]
Thanks for putting up with my mess, Dan.

Promise to do a little better, I use git every day but not nearly so much github.

**Comment by kk7ds** [comment]
So do I (git and not-github). Github is a challenge sometimes, no worries.

**Pull request merged**
