### PR TITLE
Added Wouxun kg-uvr5 support

### PR DESCRIPTION
**Pull request by gavazquez**
# CHIRP PR Guidelines

The following must be true before PRs can be merged:

1. All tests must be passing. The "PR Checks" job is speculative and failure doesn't always indicate a critial problem, but generally it needs to pass as well.
1. Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
1. Commits in a single PR should be related. Squash intermediate commits into logical units (i.e. "fix tests" commits need not survive on their own). Keep cleanup commits separate from functional changes.
1. Major new features or bug fixes should reference a [CHIRP issue](https://chirpmyradio.com/projects/chirp/issues) _in the commit message_. Do this with the pattern `Fixes #1234` or `Related to #1234` so that the ticket system links the commit to the issue.
1. Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc). The first line of every commit is emailed to the users' list after each build. It should be short, but meaningful for regular users (examples: "thd74: Fixed tone decoding" or "uv5r: Added settings support").
1. New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already). All new drivers must use `MemoryMapBytes`.
1. All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).
1. Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).

### CODE REVIEW

**Comment by kk7ds** [comment]
Please don't copy driver files. Subclass the existing implementation and only change what is necessary. That is why the PR checks test is failing. Thanks!

**Comment by gavazquez** [comment]
Will do, thanks :)

**Comment by gavazquez** [comment]
@kk7ds I think most of the style issues should be solved now.
Let me know if there's something more that needs to be fixed and I'll do it :)

**Comment by gavazquez** [comment]
@kk7ds I'm not used to program on python but let me know if there's something left to do :)

**Comment by kk7ds** [comment]
> The original 920 driver lacked several memory sections. It didn't include some fields and some internal sections like TX power, band limits, possibility to change the step size, etc. That's why you see so many changes compared to the original 920pa driver

This is why the big code lift is bad, because I couldn't see the changes.

> If you want I can make it as a new firmware totally independent on the old driver but it will of course have many similarities

Your subclass can definitely have a different `MEM_FORMAT` from the base class if it makes sense, no problem there if that's what you mean. But no, I don't want it to be totally independent - I asked to subclass, I just don't want you to (effectively) delete and re-add the original driver in the process.

> Bear in mind that memory sections for all the different 920 models are the same, only the configuration values that they have change

That means that only really get_settings needs to be different? In that case, all you need to do is unify all those differences into a helper and call it from `get_settings()` and then override that in your subclass.

**Comment by gavazquez** [comment]
Ok I might need to check out how to do the rebase as I totally messed it up :(

Regarding the code I'll try to implement what you say and upload it here and if it looks right to you I might just made a new push request

**Comment by kk7ds** [comment]
Please keep it to this PR instead of opening a new one (you haven't yet). Looks like you rebased on something much older and pushed old commits from other people in here. Just fix it and `push --force` to keep it all here.

**Pull request closed without merging**
