### PR TITLE
tdh8 add only CH mode

### PR DESCRIPTION
**Pull request by Sandmann34**
TDH8 add a new function: only CH mode

### CODE REVIEW

**Comment by kk7ds** [comment]
This looks fine, except for two things:

First, you should not need to change the images in the tree for this, and it's better if you don't to make sure you're not depending on something in them to make the tests work. Can you reset them so only the code is changed?

Second, your commit is authored by "unknown". Can you please set your identity and amend the commit?

```
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
git commit --amend --reset-author
```
Thanks. If you need help with the first one, I can fix it for you, but do the second thing for sure.

**Comment by kk7ds** [comment]
After you amend, you will need to push with `-f` to force the update into this PR.

**Comment by kk7ds** [comment]
Ah, this is why I wanted you to not change the images. It looks like your get_settings() and set_settings() are not identical so that the language isn't getting changed perhaps?

**Comment by kk7ds** [comment]
I think this is what you want. Can you confirm this works on the actual radio for both English and Chinese? If so, we can merge this.

**Comment by Sandmann34** [comment]
> 我想这就是你想要的。您能确认这在英语和中文的实际广播中都有效吗？如果是这样，我们可以合并它。

yes i tested it works.

**Comment by kk7ds** [comment]
Cool, thanks.

**Pull request merged**
