### PR TITLE
Yaesu FTnD: Issue 6151 and 10629, WiresX and special registers.

### PR DESCRIPTION
**Pull request by Darieb**
FeatureAdd #6151 WiresX settings
FeatureAdd #10629 Handle special registers. This also requires changes to Yaesu FTM3200D_R, which depends upon FT1D_R. Style and driver-test fixes are included rather than in separate commits.

# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by kk7ds** [comment]
You need to mark this as not a draft for me to take action on it!

**Comment by kk7ds** [comment]
Also note that you need to prefix issue numbers by # in order for them to be linked in redmine. Even better if you say explicitly "Fixes #xxxx" because then redmine will auto-close the issue as completed with a link to the commit.

**Comment by Darieb** [comment]
You ARE fast.  thanks.

Ah. OK. I'll recommit. Can I turn the draft into a real PR? Or must I close it and start over?

**Comment by kk7ds** [comment]
Don't create another one. I'm going to start charging you by the PR :)

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by Darieb** [comment]
I'll probably ask for a refund for every PR i've canceled. Oh, wait: you'll reasonably have applied a surcharge for those, no? I'm gonna kill the dr3.3 and dr3.1 PRs in favor of this one.

I tried to commit --amend JUST to change the commit message and then push the change up, but Git insisted that I had to pull first (and nothing changed AFAICT). SO I pulled AND pushed and it may have worked. (My ignorance is showing; I probably duplicated something yet again.

I think I've applied all the changes you'd suggested in the first two iterations.

**Comment by kk7ds** [comment]
Yeah, you've created parallel history and a merge commit in here again. Maybe I should just stop the bleeding and fix this for you. I can't always be doing that, but let me take this for the moment.

**Comment by kk7ds** [comment]
This is what your commit history looks like:

image

and this is what it should look like (after I fixed):
image

**Comment by Darieb** [comment]
Thanks. And I'm sorry. I'll be Killing my others

**Pull request merged**
