### PR TITLE
Copy memories in text format as well

### PR DESCRIPTION
**Pull request by kk7ds**
This allows for pasting into other applications for easy sharing
of memories.

### CODE REVIEW

**Comment by kk7ds** [comment]
@KC9HI I haven't done a bunch of testing to make sure this works as expected and doesn't break existing copy/paste, but it seems to be okay. Let me know what you think!

**Comment by KC9HI** [comment]
I can do more testing after supper, but everything I have tested works great.

**Comment by kk7ds** [comment]
Cool, I'll poke a little later too, but I'll wait for your blessing. Since we're relying so heavily on copy/paste we definitely don't want to break it :)

**Comment by KC9HI** [comment]
All was going well. I tested split frequencies, split tones (CTCSS & DTCS). Anything that I could program into CHIRP was exported correctly.

Then I copy-and-pasted between tabs to make sure that was working correctly. Everything looks good there.

Then I ran into a problem. I tried to copy-and-paste from an external application back to CHIRP and nothing. This is what the console shows me.

```
<wx._core.TextDataObject object at 0x0000027206CE5480>
WARNING: Failed to parse pasted data '[400.625000/136.000000]': Unable to find a frequency
<wx._core.TextDataObject object at 0x0000027206CE5480>
WARNING: Failed to parse pasted data '[400.625000/136.000000]': Unable to find a frequency
<wx._core.TextDataObject object at 0x0000027206CE5480>
WARNING: Failed to parse pasted data '[400.625000/136.000000]': Unable to find a frequency
<wx._core.TextDataObject object at 0x0000027206CE5480>
WARNING: Failed to parse pasted data '[400.625000/136.000000]': Unable to find a frequency
<wx._core.TextDataObject object at 0x0000027206CE5480>
WARNING: Failed to parse pasted data '[462.675000/+5.000000/136.5/136.5]': Unable to find a frequency
```

**Comment by kk7ds** [comment]
I was hitting the same thing, because I wasn't catching frequencies with the same number of digits as I was generating. Fixed now, and added tests to validate that our parsing is happy with our generation. Also, another bug was introduced when I moved to validating the pasted memories - empty rows fail the import test and generate errors. So that's fixed in this PR as well.

**Comment by KC9HI** [comment]
Tried to paste this to CHIRP
`[462.675000/+5.000000/136.5/136.5]`
Popup: Tx freq 5.000000 is out of supported range

So apparently parsing +5.000000 as frequency instead of offset

**Comment by kk7ds** [comment]
Ah, yeah, thanks..

**Comment by kk7ds** [comment]
Okay, added some positional awareness so it won't match something after a +/- as a tx frequency, only an offset. I'm adding all these example cases to the unit tests to make sure they're all validated (now and in the future).

**Comment by KC9HI** [comment]
`[450.000000/150.000000]`
Popup: Tx freq 5.000000 is out of supported range
`[400.000000/+9.900000]`
`[500.000000/-9.900000]`
Accepted but only shows offset of 9.000000
`[400.000000/+10.000000]`
`[500.0000
Accepted but only shows offset of 9.000000
`[400.000000/+10.000000]`
`[500.000000/-10.000000]`
Popup: 00/-10.000000]`
Popup: Tx freq 10.000000 is out of supported range

**Comment by kk7ds** [comment]
Okay, I think all of those were fixed in the second to last push except for the +9.9 issue, but I just fixed that. Excellent catches!

**Comment by KC9HI** [comment]
Getting better
'[450.000000/150.000000]'
Popup: Frequency 10.000000 is out of supported range

**Comment by kk7ds** [comment]
`[450.000000/150.000000]` works for me on the latest. Does `git rev-parse --short HEAD` show `37f1f7b3` for you? If not you're not quite on the latest.

**Comment by KC9HI** [comment]
Yes. 

C:\Users\Jim\mychirpgit\chirp>git rev-parse --short HEAD
37f1f7b3

And it still doesn't like offsets >= 10.000000

Could it be due to the radio I am using? I am loading the BTECH UV-25X2 and UV-25X4 images when testing.

**Comment by kk7ds** [comment]
Ah, yep, it's the application of the band plan rules overwriting the offset. Maybe I need to make it only do that if duplex is detected as +/- but not split.

**Comment by kk7ds** [comment]
Okay I think that's better now.

**Comment by KC9HI** [comment]
Ok. All seems to be fixed except where offset [+/-] is >= 10 MHz
`[400.000000/+100.000000]`
`[500.000000/-100.000000]`
Popup: Tx freq 100.000000 is out of supported range

**Comment by kk7ds** [comment]
Okay, but I thought there was a prohibition on splits more than like 70MHz on most radios? So I need to fix like 12MHz, but not 100Mhz, right? I don't think any of my radios can store splits more than 100MHz.

**Comment by KC9HI** [comment]
I don't know about all radio, but using the UV-5R as an example. It was programmed with a 70 (69.990) MHz limit because the VFO had a 70 MHz limit. This meant that the user couldn't use the VFO mode for splits larger than 70 MHz or cross band operation. This was later change to allow the user to set the VFO offset to 999.99 MHz. But the radio channels have always supported a repeater offset as high as the "offset" between the band limits. So the 70 MHz limit programmed into CHIRP is arbitrary and has never matched the capability of the radio. I noticed that there are many driver that contain this 70 MHz limit. I know on at least one driver I set it up to where if the 2 frequencies are in the same band, I have CHIRP convert it to (+/-) offset and if they are in different band split / tx frequency.

**Comment by kk7ds** [comment]
Okay, I'm thinking mostly of the japanese radios that actually store an offset instead of emulating it. I guess because I require the +/- to come before the offset (and not a txfreq) then I should be able to allow for up to 999MHz offsets. In a bit I'll do that and add some tests and push up if so.

**Comment by KC9HI** [comment]
I always wondered what the reason for the 70 MHz limit was. You explanation makes perfect sense.

**Comment by kk7ds** [comment]
Okay, so supporting >10 and especially >100MHz splits makes the matching confuse tone values (like 88.5, 162.2) for offsets in strings like "440.35 + 162.2" which worked before. I think that non-standard splits working in this best-effort copy/paste stuff are probably not that important and so we'll be correct a lot more often if we only support offsets like 0.6, 1.2, 5.0, etc. Do you think that's okay?

I should also probably make the string we generate when we copy for external programs not have so many digits on the offset in that case as that is really where some of this complexity is coming from.

**Comment by KC9HI** [comment]
Yes. Common offsets should be fine. Anything other then the common 0.6, 1.6, 5.0, etc. is probably going to be formatted as rx_freq/tx_freq anyway.

**Comment by kk7ds** [comment]
Yeah, I think the only example I can think of is the 33cm band which uses 25MHz offsets. But that could be noted as tx/rx as you say.

If this catches on, I can parse the `[a/b/c/d]` format specifically and then all these problems go away. I'm just trying to make the "copy and paste generic stuff from a website" parsing code as smart as it can be, but there are limits to how well it can do.

**Comment by KC9HI** [comment]
If I past this faux frequency/offset into CHIRP the offset is change to 1.000000 MHz
`[500.000000/-1.600000]`
However, If I use this valid ham repeater from RepeaterBook, it is entered fine.
`224.6400 | -1.6 MHz | 107.2 / CSQ`

**Comment by kk7ds** [comment]
Yeah, I changed the offsets in that format to only three decimal digits, so `0.6`, `0.60`, `0.600` and `5.000` - anything longer like `0.6000` won't match which helps distinguish between other formats. Everything I've seen on people's websites seems to be short enough that three digits suffices. Copy from chirp should use three decimal digits now too.

Sounds like we should be good now, thanks very much for helping stress test that!

**Comment by KC9HI** [comment]
Yep. Taking that into account. Everything work!

**Comment by KC9HI** [comment]
Well except when you go from CHIRP to external app the result is -1.600000 (which won't cut-and-paste back in)

**Comment by kk7ds** [comment]
Yep, crap. When I said "I shortened offset to three digits" I meant I did that in the parsing code in the commit, and in the generation code in my *mind* :)

**Comment by KC9HI** [comment]
That's got it.

**Pull request merged**
