### PR TITLE
uv5r.py: work-in-progress - proposed solution for #10505

### PR DESCRIPTION
**Pull request by KC9HI**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).
* All files must be GPLv3 licensed or contain no license verbiage. No additional restrictions can be placed on the usage (i.e. such as noncommercial).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by KC9HI** [comment]
@kk7ds I need another set of eyes to look at this. I am trying to get 'Settings -> Other Settings -> Power-On Message' to not pop-up the set_warning() message. It is not stored in Aux memory so it doesn't need the message.

I have been trying to solve this all day. If the solution is not simple, I can move the setting to a different tab or just live with the pop-up message.

Thanks

**Comment by KC9HI** [comment]
You can probably use the Baofeng_UV-5R.img for testing.

**Comment by kk7ds** [comment]
It was an obscure bug in the settings editor itself actually! To be clear, I assume you want to remove the two set_warning() lines either always or some of the time right? AFAICT, in this patch you're always setting it anyway. I commented out the two poweron `set_warning` lines and saw that it *still* warned. That's the problem you were hitting right? Try with the commit I put in front, as I think it should be good now.

**Comment by KC9HI** [comment]
The Power-On Message Line 1/Line 2 are to still get warned. It is only the Power-On Message setting right under them (chooses between Full and Message) that is not supposed to get a warning. But that's OK. I can fix it back after I test. Thanks.

**Comment by kk7ds** [comment]
Ah, okay makes sense. Well, it's the same issue so should be good now.

**Comment by KC9HI** [comment]
Look good to me. I took a lot of radios and a lot of time staring at images to identify the specific radios that have the issue and a workaround that makes them behave.  I found at least 2 in the nearly dozen radios that I acquired. I wanted to iron out this small issue before I attached a copy to the issue for testing. Now I should be able to do that tonight (or possibly tomorrow).

**Pull request closed without merging**
