### PR TITLE
Quanshen UV-K5 driver for egzumer custom firmware

### PR DESCRIPTION
**Pull request by egzumer**
Driver repo: https://github.com/egzumer/uvk5-chirp-driver
Firmware repo: https://github.com/egzumer/uv-k5-firmware-custom

### CODE REVIEW

**Comment by kk7ds** [comment]
It looks to me like you've just fully duplicated the driver and changed ... what exactly? There should be a chirp issue for this referenced in the commit message.

We've already discussed the many firmware variants and we just can't include duplicate drivers for everyone's firmware, or even expose them as different models. It's a maintenance nightmare. The firmware developers for these radios have got to figure out a way to expose which model/features/version is in a radio so that CHIRP can do the right thing.

If you can subclass the existing driver and tell the difference between the OEM K5 and the different firmware, we can definitely include your custom driver. But we can't just duplicate the file in the tree every time and make a few edits. Please, help us keep this sane.

cc: @sq5bpf

**Comment by egzumer** [comment]
I put enough time into making it go through all of the tests (not counting the driver itself), I'm tired, I'm not going to put any more time into it. If there is no will to integrate it, that is fine, I'll continue to release my own driver in my own repo.

**Comment by kk7ds** [comment]
Come on, please, let's work together here. I'm sure you can understand that having a bunch of duplicated code isn't helpful for long-term maintenance. I'm certainly willing to help massage this into place if need-be.

Can this driver tell the difference between a stock K5 and your modified firmware when it goes to clone? Meaning, can your driver recognize and refuse to clone in/out of a stock K5 so the user has to choose the right model?

**Comment by egzumer** [comment]
There is a different version string by which the driver can distinguish one firmware from the other, but it doesn't do that right now.
Original is like `k5_2.01.27`
Mine is like `EGZUMER v0.21`

Modified driver contains more options in some features, and some features that are not present in the original firmware.
It was refactored in many places. My firmware can be built from source with different build options that turn on and off some features, there are bits set in a memory that the driver reads and shows or hides corresponding configuration options. Calibration data editing was added.

**Comment by kk7ds** [comment]
> There is a different version string by which the driver can distinguish one firmware from the other, but it doesn't do that right now. Original is like `k5_2.01.27` Mine is like `EGZUMER v0.21`

Okay, my OEM (and never upgraded ones) have a firmware string of `app_2.01.17` ... Does that mean we should allow either `app_` or `k5_` as suitable prefixes for the OEM driver?

> Modified driver contains more options in some features, and some features that are not present in the original firmware. It was refactored in many places. My firmware can be built from source with different build options that turn on and off some features, there are bits set in a memory that the driver reads and shows or hides corresponding configuration options. Calibration data editing was added.

Yes, I've been looking at the diff. There are plenty of "gardening" changes that would be nice to apply to the OEM driver, and I see the extra stuff.

I think I can refactor the base driver to allow yours to subclass the base driver and override what you need, as well as add the firmware checking to make sure we don't allow the user to upload an image from your firmware to an OEM radio (and vice versa). That will reduce the delta quite a bit and allow sharing of the things that are still shared. I won't be able to do much until next week, but I can start on it then, okay?

**Comment by egzumer** [comment]
> Does that mean we should allow either `app_` or `k5_` as suitable prefixes for the OEM driver?

I've checked 3 stock K6 radios I have, each was different: `k5_2.01.27`, `2.01.31`, `2.01.32` (no `k5_` part)

> I won't be able to do much until next week, but I can start on it then, okay?

There is no rush whatsoever. If you pave the way I'll try to help.

**Comment by kk7ds** [comment]
> > Does that mean we should allow either `app_` or `k5_` as suitable prefixes for the OEM driver?
> 
> I've checked 3 stock K6 radios I have, each was different: `k5_2.01.27`, `2.01.31`, `2.01.32` (no `k5_` part)

Oof, okay, so maybe it was `app_` originally, then `k5_` and then just dropped the prefix sometime between 27 and 31? I'll check for just x.y.z as well. Perhaps we'll have to break a few people to gather more samples...

@sq5bpf maybe you have some additional samples?

> There is no rush whatsoever. If you pave the way I'll try to help.

Ack. I flashed one of my K5s to your firmware and have some preliminary changes that make chirp able to select the right class without the user having to know which they have, which is the ideal situation I much prefer. I know @sq5bpf wanted to be able to have more customized behavior for modified firmwares, and this should make it easy to spread out from there. I'll start refactoring and rebasing more seriously next week.

**Comment by egzumer** [comment]
Other FW versions:

k5_2.01.19
k5_2.01.23
k5_2.01.25
k5_4.00.01
4.00.07
k5_3.00.10
3.00.15
k5_2.01.27
2.01.31
2.01.32
4.00.06

**Comment by kk7ds** [comment]
> Other FW versions:
> 
> k5_2.01.19 k5_2.01.23 k5_2.01.25 k5_4.00.01 4.00.07 k5_3.00.10 3.00.15 k5_2.01.27 2.01.31 2.01.32 4.00.06

Are those from OEM devices or modified firmwares?

**Comment by egzumer** [comment]
OEM: https://github.com/amnemonic/Quansheng_UV-K5_Firmware/tree/main/firmware

I tried (amongst the others) RT590_v2.01.27_publish.bin, RT590_v2.01.32_publish.bin, RT600_v4.00.06_publish.bin
`4.*` is in UV-5R I think, but it is the same as some `2.*`, just different version string, `3.*` don't know (some of the K6?), but it also is just a different version string

**Comment by kk7ds** [comment]
Ugh, okay. Well, someone more familiar with this radio will have to decide if the base driver (which has been allowing any of those firmwares up until now) should continue to allow those, or if we need to pull some of them out to different subclasses. Reasons for that would be to (a) make the vendor/model correct and (b) if they have any different features (like GMRS-only, band limit changes, etc).

But, I can try to make the current driver agree to recognize those for the moment so at least nothing changes unless we intend to change.

**Comment by egzumer** [comment]
Quansheng UV-K5, UV-5R, UV-K6 (vel K5(8)),
Retevis RT590, 
Radtel RT600,
and some other...

Those are all the same radio, have identical pcb and software. There are no different features in different OEM firmwares.

**Comment by kk7ds** [comment]
Not done yet, but I'm showing my work. I will collapse my WIP patch and your original proposal, but I'm keeping the delta separate for the moment so you can see the changes I'm making easily.

**Comment by kk7ds** [comment]
@egzumer This is what I propose which is pretty close to what I was hoping for. I wish there was more sharing between the settings, but there's so much divergence there (some of which is critical) that it'll be a lot of change to make. I plan to further squash two of the cleanups into the base driver for things that I want fixed in the first commit, but left them broken out here so you can see them.

Do you want to review/test this first or should I just finish squashing and merge and we can roll from here?

**Comment by joc2** [comment]
HI , i try the last release of chirp ( 3 feb 2024) ( it show that version egzumer is supported )
 with version egzumer 0,22 in the radio
image


when download the radio, chirp load it as a regular uv-k5 and all feature of egzumer is missing
 
from what i see, kk7ds release it yesterday, and close this request,
Let me know.

**Comment by kk7ds** [comment]
Please open a ticket on the chirp tracker and include debug logs and images per those instructions and I'll take a look.

**Comment by joc2** [comment]
it's created

Demande [#11123](https://chirp.danplanet.com/issues/11123) créée

by the way, the size of the buffer for the firmware version is to small.  it cut the last info...   increase buffer to 32 at lease for the futur detail version ....,

has the uv-k5 original driver has this problem... that i have change in the egzumer driver to correct that
see the full debug file in the request 11123

image

image

**Comment by kk7ds** [comment]
Just to close the loop here in case anyone finds this later, here's the bug:

https://chirp.danplanet.com/issues/11123

It turns out @joc2 was still running an old version. After running today's version, the egzumer version is detected properly.

**Comment by egzumer** [comment]
I've finally had time to sit and analyze the changes. You removed "comment lines" from configuration (disabled options that were used as additional description). First of all this created some issues:
* marked with 1 - names are duplicated unnecessarily.
* marked with 2 - band name is missing, and now you can't tell what's what.

Is this how you prefer it to be? Because I liked it much better how it was before. Squelch values were all on the same page and you could see all the values at once without clicking through.

Screen Shot 02-04-24 at 06 48 PM

Also "Basic Settings" had options grouped with those comments in groups of similar settings.

Screen Shot 02-04-24 at 07 30 PM

**Comment by kk7ds** [comment]
No, it's not how I prefer it to look, I just prefer not to have the drivers assume and override the presentation that is the job of the UI. Over the 15+ years we've been through multiple changes in the UI and various other organizational elements and these sorts of things are always the ones that break when we have to make those changes since they assume things about how the UI works. So, just trying to make sure the driver can be healthy and maintainable going forward. Those "comment" lines wouldn't have worked at all in the UI we had util a few years ago, for example.

I'm working on making this expressable by the driver so it works more like you originally had it, and I'm using your driver to develop and test that. Here's what it looks like now:

https://chirp.danplanet.com/issues/11127#note-1

The duplication in the squelch things was a bug I introduced, which I noticed while working on the above and have fixed in #901. I have a little more I need to do on that, which I might not get to today. But hopefully you like that better (and maybe better than what you had before, since they're collapse-able). Let me know what you think.

**Comment by egzumer** [comment]
>  Here's what it looks like now:

This is perfect, I didn't have the courage to ask about it, at some point I tried to look into how to implement that myself and contribute, but I'm not knowledgeable enough and I gave up. Very much looking forward to that. I withdraw my objections in that case.

**Comment by kk7ds** [comment]
> This is perfect, I didn't have the courage to ask about it, at some point I tried to look into how to implement that myself and contribute, but I'm not knowledgeable enough and I gave up. Very much looking forward to that.

Cool, it's been on my todo list for a while. Some of the other use-cases of it were less compelling but yours was pretty extreme so it seemed time to get it done.

I also need to add a way to expose the explanations of the settings in the UI. We had that before but aren't currently exposing them. Also on my todo list, and seems like a lot of your stuff (especially the calibrations) could probably use more help text available to the user. Not entirely sure how I'll do that, but just FYI it's on my radar.

> I withdraw my objections in that case.

LOL, excellent :)

**Pull request merged**
