### PR TITLE
update ja_JP locale

### PR DESCRIPTION
**Pull request by weboo**
I have updated the Japanese translation and adding some translation targets.
I would be happy to reflect them if there is no problem.

### CODE REVIEW

**Comment by weboo** [comment]
It seems to be stuck in the PEP8 style check, should I fix this?

**Comment by kk7ds** [comment]
I'd like to keep the changes to the K5 driver as a separate commit from updating the jp locale itself.

Mind if I split that stuff up for you and push it here?

**Comment by weboo** [comment]
I split that commit in two. Please check it.

**Comment by kk7ds** [comment]
Yep, perfect, thanks. I just tweaked the commit message on the first one to mention which driver was affected. Will merge this for tomorrow.

**Comment by weboo** [comment]
Thank you very much for your support.

**Pull request merged**
