### PR TITLE
Add WiresX settings display and mods

### PR DESCRIPTION
**Pull request by Darieb**
# CHIRP PR Checklist

The following must be true before PRs can be merged:

* All tests must be passing.
* Commits should be squashed into logical units.
* Commits should be rebased (or simply rebase-able in the web UI) on current master. Do not put merge commits in a PR.
* Commits in a single PR should be related.
* Major new features or bug fixes should reference a [CHIRP issue](https://chirp.danplanet.com/projects/chirp/issues).
* New drivers should be accompanied by a test image in `tests/images` (except for thin aliases where the driver is sufficiently tested already).

Please also follow these guidelines:

* Keep cleanups in separate commits from functional changes.
* Please write a reasonable commit message, especially if making some change that isn't totally obvious (such as adding a new model, adding a feature, etc).
* Do not add new py2-compatibility code (No new uses of `six`, `future`, etc).
* All new drivers should set `NEEDS_COMPAT_SERIAL=False` and use `MemoryMapBytes`.
* New drivers and radio models will affect the Python3 test matrix. You should regenerate this file with `tox -emakesupported` and include it in your commit.

### CODE REVIEW

**Comment by Darieb** [comment]
This is the FT1D driver that balks when I try to change a special register. It was again a multiple-commit process.

**Comment by Darieb** [comment]
Add WiresX settings display and mods, Issue #6151, along with changes
    to APRS settings to match WiresX hierarchal menus.

**Comment by kk7ds** [comment]
In case you didn't see this needs a rebase and potentially a conflict resolution. It might just be complaining because you've got the settings menu setup commit in this, but it was already merged in the other PR.

**Comment by Darieb** [comment]
Oh my stars and garters. Now it doesn't like that I amended the commit comment! the PR check dies again (or still?) I may need to go to remedial GIT school just to understand. :^((

**Comment by Darieb** [comment]
I tried a "ready for review" and it legacy code test fails.

**Comment by kk7ds** [comment]
Right, you've got a bunch of merge commits in this now, but also, this is an earlier PR with earlier versions of the commits that I just merged from your *latest* PR, so the commits in this PR can never be rebased on master without conflicts (nor does it makes sense to, since that content is already in the tree).

But yeah, I think maybe some review of git and github docs would be in order. You should never be doing a merge commit if you're submitting to my repo, which is why the PR checks are failing. Any time you do a merge commit it means you've forked history and are collapsing it again, which brings the opportunity for what you've seen-lots of duplication and confusion in the commit history. I keep the chirp history as linear as possible and thus any time you see a merge commit in your PR, you need to rebase it out.

**Pull request closed without merging**
